server {
    listen 80;
    server_name localhost;

    root /www/wwwroot;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
    }

    location /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
    }

    location /user/tool/ittool/ {
        alias /www/wwwroot/;
        index index.html;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
    }
}
